site_name: "MkDocs Data Plugin Documentation"
site_author: "Joan Puigcerver Ibáñez"
site_url: https://joapuiib.github.io/mkdocs-data-plugin/
repo_name: joapuiib/mkdocs-data-plugin
repo_url: https://github.com/joapuiib/mkdocs-data-plugin

watch:
  - data

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joapuiib
      name: joapuiib @ GitHub

exclude_docs: |
  _*

theme:
  name: material
  icon:
    logo: material/file-send-outline
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: deep purple
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: deep purple
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.follow
    - search.share
    - search.suggest

plugins:
  - search
  - alias:
      use_anchor_titles: true
  - data
  - macros
  - social
  - tags
  - git-revision-date-localized

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - sane_lists
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.html
  - pymdownx.blocks.caption
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.fancylists:
      inject_class: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home:
    - index.md
    - installation.md
  - Configuration:
    - configuration/index.md
